{"name": "test_invalid_login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n\tGetHandleVerifier [0x0046EC13+23731]\n\t(No symbol) [0x003FC394]\n\t(No symbol) [0x002DBE63]\n\t(No symbol) [0x0031FCE6]\n\t(No symbol) [0x0031FF2B]\n\t(No symbol) [0x0035D892]\n\t(No symbol) [0x00341EA4]\n\t(No symbol) [0x0035B46E]\n\t(No symbol) [0x00341BF6]\n\t(No symbol) [0x00313F35]\n\t(No symbol) [0x00314EBD]\n\tGetHandleVerifier [0x0074F0D3+3039603]\n\tGetHandleVerifier [0x00762DEA+3120778]\n\tGetHandleVerifier [0x0075B592+3089970]\n\tGetHandleVerifier [0x005043B0+635984]\n\t(No symbol) [0x00404DCD]\n\t(No symbol) [0x00402068]\n\t(No symbol) [0x00402205]\n\t(No symbol) [0x003F4FD0]\n\tBaseThreadInitThunk [0x76A4FCC9+25]\n\tRtlGetAppContainerNamedObjectPath [0x7711809E+286]\n\tRtlGetAppContainerNamedObjectPath [0x7711806E+238]", "trace": "self = <TestCases.test_login.Test_Invalid_Login object at 0x0000029B1ECAB670>\n\n    @allure.description(\"Validate invalid login credentials.\")\n    @allure.severity(severity_level=\"Normal\")\n    def test_invalid_login(self):\n        self.driver.get(base_url)\n>       Login_Page(self.driver).login(username, invalid_psw)\n\nTestCases\\test_login.py:45: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nWebPages\\LoginPage.py:17: in login\n    self.element_sendkeys_until(self.username_ele,username)\nBasicFunctions\\selenium_functions.py:10: in element_sendkeys_until\n    WebDriverWait(self.driver,10).until(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"f4803b7cf666aec970d912d34386067c\")>\nmethod = <function visibility_of_element_located.<locals>._predicate at 0x0000029B1E593B50>, message = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            if time.monotonic() > end_time:\n                break\n            time.sleep(self._poll)\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       \tGetHandleVerifier [0x0046EC13+23731]\nE       \t(No symbol) [0x003FC394]\nE       \t(No symbol) [0x002DBE63]\nE       \t(No symbol) [0x0031FCE6]\nE       \t(No symbol) [0x0031FF2B]\nE       \t(No symbol) [0x0035D892]\nE       \t(No symbol) [0x00341EA4]\nE       \t(No symbol) [0x0035B46E]\nE       \t(No symbol) [0x00341BF6]\nE       \t(No symbol) [0x00313F35]\nE       \t(No symbol) [0x00314EBD]\nE       \tGetHandleVerifier [0x0074F0D3+3039603]\nE       \tGetHandleVerifier [0x00762DEA+3120778]\nE       \tGetHandleVerifier [0x0075B592+3089970]\nE       \tGetHandleVerifier [0x005043B0+635984]\nE       \t(No symbol) [0x00404DCD]\nE       \t(No symbol) [0x00402068]\nE       \t(No symbol) [0x00402205]\nE       \t(No symbol) [0x003F4FD0]\nE       \tBaseThreadInitThunk [0x76A4FCC9+25]\nE       \tRtlGetAppContainerNamedObjectPath [0x7711809E+286]\nE       \tRtlGetAppContainerNamedObjectPath [0x7711806E+238]\n\n..\\..\\..\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:105: TimeoutException"}, "description": "Validate invalid login credentials.", "start": 1735706505415, "stop": 1735706523286, "uuid": "f1e314e8-5ded-40ee-8a60-f5122c640d4a", "historyId": "31c5a7146fa87ec2f850c58f550abd71", "testCaseId": "31c5a7146fa87ec2f850c58f550abd71", "fullName": "TestCases.test_login.Test_Invalid_Login#test_invalid_login", "labels": [{"name": "severity", "value": "Normal"}, {"name": "tag", "value": "@pytest.mark.usefixtures('browser_setup')"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_Invalid_Login"}, {"name": "host", "value": "Win10-2022VRASL"}, {"name": "thread", "value": "7344-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login"}]}